### ISSUE TITLE
BPE not cached

### ISSUE THREAD

**Issue by wwnew** [lab-ml/python_autocomplete#2]
hello, when I tried to training this model, it raised RuntimeError('BPE not cached'). I really wanna know why it happened.  Thanks

**Comment by vpj** [comment]
@wwnew hey sorry forgot to reply. You need to build the BPE vocabulary first (we need to update this in the readme). Did you manage to get it working?

**Comment by wwnew** [comment]
Thanks for your reply.  After I opened the issue，I had realized that I didn't run the script to generate the vocabulary. And It works now😄😄

**Comment by geekeedatascience** [comment]
@wwnew how you generate the vocabulary?
